name: Format Code

on: [pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              env:
                CGO_ENABLED: 1
            - run: go fmt
            - name: go generate (clang-format)
              env:
                CGO_ENABLED: 1
              run: go generate
            - name: Display missing format changes
              env:
                CGO_ENABLED: 1
              run: git diff --exit-code
