name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Tests on ${{ matrix.go-version }} ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [1.18.10, 1.19.5]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Go Test
      env:
        CGO_CXXFLAGS: "-Werror"
      run: go test -v -coverprofile c.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      env:
        OS: ${{ matrix.platform }}
        GO: ${{ matrix.go-version }}
      with:
        files: ./c.out
        env_vars: OS,GO
        
